<?php
#
# WARNING: This file is autogenerated, do not modify.
#

$metadata['google.com'] = array(
	'AssertionConsumerService'	=> array('https://www.google.com/a/%(domain)s/acs'),
	'NameIDFormat'	=> 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
	'simplesaml.nameidattribute'	=> 'univentionGoogleAppsPrimaryEmail',
	'attributes'	=> array('univentionGoogleAppsEnabled', 'univentionGoogleAppsPrimaryEmail'),
	'OrganizationName'	=> 'Google Apps for Work',
	'privacypolicy'	=> 'http://support.google.com/a/bin/answer.py?hl=en&answer=60762',
	'authproc' => array(
		10 => array(
		'class' => 'authorize:Authorize',
		'regex' => FALSE,
		'univentionGoogleAppsEnabled' => '1',
		)
	),
	70 => array(
		'class' => 'core:AttributeLimit',
		''
	),
);
